Popcorn version 1.0
(C) 2015-2019 Brielin C Brown
University of California, Berkeley
GNU General Public License v3

Invoking command: python /usr/local/bin/popcorn fit -v 1 --gen_effect --cfile /content/Popcorn/EUR_EAS_all_gen_eff.cscore --sfile1 /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/SLE2021_eur_af1000_v1.txt.gz --sfile2 /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/SLE2021_eas_af1000_v1.txt.gz /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/result/SLE_EUR_EAS
Beginning analysis at Sun Jul 28 13:21:01 2024
Traceback (most recent call last):
  File "/usr/local/bin/popcorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/popcorn/__main__.py", line 185, in main
    with open(args.cfile,'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/content/Popcorn/EUR_EAS_all_gen_eff.cscore'
Popcorn version 1.0
(C) 2015-2019 Brielin C Brown
University of California, Berkeley
GNU General Public License v3

Invoking command: python /usr/local/bin/popcorn fit -v 1 --gen_effect --cfile /content/Popcorn/EUR_EAS_all_gen_eff.cscore --sfile1 /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/SLE2021_eur_af1000_v1.txt.gz --sfile2 /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/SLE2021_eas_af1000_v1.txt.gz /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/result/SLE_EUR_EAS
Beginning analysis at Sun Jul 28 13:21:30 2024
Analyzing a pair of traits in two populations
Traceback (most recent call last):
  File "/usr/local/bin/popcorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/popcorn/__main__.py", line 206, in main
    data = sumstats.sumstats_2_trait(scores,args)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/sumstats.py", line 170, in __init__
    data1, id_type1 = self.parse_input(args.sfile1)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/sumstats.py", line 48, in parse_input
    DF = pd.read_table(sfile)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1242, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/common.py", line 753, in get_handle
    handle = gzip.GzipFile(  # type: ignore[assignment]
  File "/usr/lib/python3.10/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Popcorn/SLE_EUR_EAS/SLE2021_eur_af1000_v1.txt.gz'
Popcorn version 1.0
(C) 2015-2019 Brielin C Brown
University of California, Berkeley
GNU General Public License v3

Invoking command: python /usr/local/bin/popcorn fit -v 1 --gen_effect --cfile /content/Popcorn/EUR_EAS_all_gen_eff.cscore --sfile1 /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/SLE2015_eur_af1000_v1.txt.gz --sfile2 /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/SLE2021_eas_af1000_v1.txt.gz /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/result/SLE_EUR_EAS
Beginning analysis at Sun Jul 28 13:22:29 2024
Analyzing a pair of traits in two populations
Note: Study AF not provided. Defulating to ignoring variants where minor allele is the compliment of the major allele.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'beta'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/popcorn/sumstats.py", line 86, in parse_input
    data['beta'] = DF['beta']
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'beta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Z'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/popcorn/sumstats.py", line 91, in parse_input
    data['Z'] = DF['Z']
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'Z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'OR'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/popcorn/sumstats.py", line 95, in parse_input
    DF['OR'].values, DF['p-value'].values)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'OR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/popcorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/popcorn/__main__.py", line 206, in main
    data = sumstats.sumstats_2_trait(scores,args)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/sumstats.py", line 170, in __init__
    data1, id_type1 = self.parse_input(args.sfile1)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/sumstats.py", line 100, in parse_input
    raise ValueError(
ValueError: Must provide either signed Z-scores 1) "Z", 2) "beta" and "SE", or 3) "OR" and "p-value"
Popcorn version 1.0
(C) 2015-2019 Brielin C Brown
University of California, Berkeley
GNU General Public License v3

Invoking command: python /usr/local/bin/popcorn fit -v 1 --gen_effect --cfile /content/Popcorn/EUR_EAS_all_gen_eff.cscore --sfile1 /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/SLE2015_eur_af1000_v1.txt.gz --sfile2 /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/SLE2021_eas_af1000_v1.txt.gz /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/result/SLE_EUR_EAS
Beginning analysis at Sun Jul 28 13:26:14 2024
Analyzing a pair of traits in two populations
Note: Study AF not provided. Defulating to ignoring variants where minor allele is the compliment of the major allele.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'beta'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/popcorn/sumstats.py", line 86, in parse_input
    data['beta'] = DF['beta']
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'beta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Z'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/popcorn/sumstats.py", line 91, in parse_input
    data['Z'] = DF['Z']
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'Z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'OR'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/popcorn/sumstats.py", line 95, in parse_input
    DF['OR'].values, DF['p-value'].values)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'OR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/popcorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/popcorn/__main__.py", line 206, in main
    data = sumstats.sumstats_2_trait(scores,args)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/sumstats.py", line 170, in __init__
    data1, id_type1 = self.parse_input(args.sfile1)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/sumstats.py", line 100, in parse_input
    raise ValueError(
ValueError: Must provide either signed Z-scores 1) "Z", 2) "beta" and "SE", or 3) "OR" and "p-value"
Popcorn version 1.0
(C) 2015-2019 Brielin C Brown
University of California, Berkeley
GNU General Public License v3

Invoking command: python /usr/local/bin/popcorn fit -v 1 --gen_effect --cfile /content/Popcorn/EUR_EAS_all_gen_eff.cscore --sfile1 EUR.txt.gz --sfile2 EAS.txt.gz /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/result/SLE_EUR_EAS
Beginning analysis at Sun Jul 28 13:53:08 2024
Analyzing a pair of traits in two populations
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'N'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/popcorn/sumstats.py", line 82, in parse_input
    data['N'] = DF['N']
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'N'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/popcorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/popcorn/__main__.py", line 206, in main
    data = sumstats.sumstats_2_trait(scores,args)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/sumstats.py", line 170, in __init__
    data1, id_type1 = self.parse_input(args.sfile1)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/sumstats.py", line 84, in parse_input
    raise ValueError('Must provide number of samples "N"')
ValueError: Must provide number of samples "N"
Popcorn version 1.0
(C) 2015-2019 Brielin C Brown
University of California, Berkeley
GNU General Public License v3

Invoking command: python /usr/local/bin/popcorn fit -v 1 --gen_effect --cfile /content/Popcorn/EUR_EAS_all_gen_eff.cscore --sfile1 EUR.txt.gz --sfile2 EAS.txt.gz /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/result/SLE_EUR_EAS
Beginning analysis at Sun Jul 28 13:58:42 2024
Analyzing a pair of traits in two populations
5723320 4297754 SNPs detected in input.
2735919 SNPs remaining after merging with score file.
2735919 SNPs remaining after filtering on AF and self-compliment SNPs.
Initial estimate:
       Val (obs)  SE
h1^2   0.162018 NaN
h2^2   0.132732 NaN
pg     1.038895 NaN
Performing jackknife estimation of the standard error using 200 blocks of size 13679 .
Jackknife iter: 1 /usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py:44: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  k = np.ones((x.shape[0]),dtype=np.bool)
Traceback (most recent call last):
  File "/usr/local/bin/popcorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/popcorn/__main__.py", line 218, in main
    res = fit.fit_pg(data.data,args,M=M)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/fit.py", line 241, in __init__
    self.jackknife = jackknife.jackknife(close_call,data,res,args)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py", line 19, in __init__
    self.psuedovalues, self.delete_values = self.jackknife(f,x,r)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py", line 44, in jackknife
    k = np.ones((x.shape[0]),dtype=np.bool)
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 319, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
Popcorn version 1.0
(C) 2015-2019 Brielin C Brown
University of California, Berkeley
GNU General Public License v3

Invoking command: python /usr/local/bin/popcorn fit -v 1 --gen_effect --cfile /content/Popcorn/EUR_EAS_all_gen_eff.cscore --sfile1 EUR.txt.gz --sfile2 EAS.txt.gz /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/result/SLE_EUR_EAS
Beginning analysis at Sun Jul 28 14:07:43 2024
Analyzing a pair of traits in two populations
5723320 4297754 SNPs detected in input.
2735919 SNPs remaining after merging with score file.
2735919 SNPs remaining after filtering on AF and self-compliment SNPs.
Initial estimate:
       Val (obs)  SE
h1^2   0.162018 NaN
h2^2   0.132732 NaN
pg     1.038895 NaN
Performing jackknife estimation of the standard error using 200 blocks of size 13679 .
Jackknife iter: 1 /usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py:44: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  k = np.ones((x.shape[0]),dtype=np.bool)
Traceback (most recent call last):
  File "/usr/local/bin/popcorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/popcorn/__main__.py", line 218, in main
    res = fit.fit_pg(data.data,args,M=M)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/fit.py", line 241, in __init__
    self.jackknife = jackknife.jackknife(close_call,data,res,args)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py", line 19, in __init__
    self.psuedovalues, self.delete_values = self.jackknife(f,x,r)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py", line 44, in jackknife
    k = np.ones((x.shape[0]),dtype=np.bool)
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 319, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
Popcorn version 1.0
(C) 2015-2019 Brielin C Brown
University of California, Berkeley
GNU General Public License v3

Invoking command: python /usr/local/bin/popcorn fit -v 1 --gen_effect --cfile /content/Popcorn/EUR_EAS_all_gen_eff.cscore --sfile1 EUR.txt.gz --sfile2 EAS.txt.gz /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/result/SLE_EUR_EAS
Beginning analysis at Sun Jul 28 14:27:38 2024
Analyzing a pair of traits in two populations
5723320 4297754 SNPs detected in input.
2735919 SNPs remaining after merging with score file.
2735919 SNPs remaining after filtering on AF and self-compliment SNPs.
Initial estimate:
       Val (obs)  SE
h1^2   0.162018 NaN
h2^2   0.132732 NaN
pg     1.038895 NaN
Performing jackknife estimation of the standard error using 200 blocks of size 13679 .
Jackknife iter: 1 /usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py:44: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  k = np.ones((x.shape[0]),dtype=np.bool)
Traceback (most recent call last):
  File "/usr/local/bin/popcorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/popcorn/__main__.py", line 218, in main
    res = fit.fit_pg(data.data,args,M=M)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/fit.py", line 241, in __init__
    self.jackknife = jackknife.jackknife(close_call,data,res,args)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py", line 19, in __init__
    self.psuedovalues, self.delete_values = self.jackknife(f,x,r)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py", line 44, in jackknife
    k = np.ones((x.shape[0]),dtype=np.bool)
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 319, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
Popcorn version 1.0
(C) 2015-2019 Brielin C Brown
University of California, Berkeley
GNU General Public License v3

Invoking command: python /usr/local/bin/popcorn fit -v 1 --gen_effect --cfile /content/Popcorn/EUR_EAS_all_gen_eff.cscore --sfile1 EUR.txt.gz --sfile2 EAS.txt.gz /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/result/SLE_EUR_EAS
Beginning analysis at Sun Jul 28 14:30:36 2024
Analyzing a pair of traits in two populations
5723320 4297754 SNPs detected in input.
2735919 SNPs remaining after merging with score file.
2735919 SNPs remaining after filtering on AF and self-compliment SNPs.
Initial estimate:
       Val (obs)  SE
h1^2   0.162018 NaN
h2^2   0.132732 NaN
pg     1.038895 NaN
Performing jackknife estimation of the standard error using 200 blocks of size 13679 .
Jackknife iter: 1 /usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py:44: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  k = np.ones((x.shape[0]),dtype=np.bool)
Traceback (most recent call last):
  File "/usr/local/bin/popcorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/popcorn/__main__.py", line 218, in main
    res = fit.fit_pg(data.data,args,M=M)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/fit.py", line 241, in __init__
    self.jackknife = jackknife.jackknife(close_call,data,res,args)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py", line 19, in __init__
    self.psuedovalues, self.delete_values = self.jackknife(f,x,r)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py", line 44, in jackknife
    k = np.ones((x.shape[0]),dtype=np.bool)
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 319, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
Popcorn version 1.0
(C) 2015-2019 Brielin C Brown
University of California, Berkeley
GNU General Public License v3

Invoking command: python /usr/local/bin/popcorn fit -v 1 --gen_effect --cfile /content/Popcorn/EUR_EAS_all_gen_eff.cscore --sfile1 EUR.txt.gz --sfile2 EAS.txt.gz /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/result/SLE_EUR_EAS
Beginning analysis at Sun Jul 28 14:34:55 2024
Analyzing a pair of traits in two populations
5723320 4297754 SNPs detected in input.
2735919 SNPs remaining after merging with score file.
2735919 SNPs remaining after filtering on AF and self-compliment SNPs.
Initial estimate:
       Val (obs)  SE
h1^2   0.162018 NaN
h2^2   0.132732 NaN
pg     1.038895 NaN
Performing jackknife estimation of the standard error using 200 blocks of size 13679 .
Jackknife iter: 1 /usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py:44: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  k = np.ones((x.shape[0]),dtype=np.bool)
Traceback (most recent call last):
  File "/usr/local/bin/popcorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/popcorn/__main__.py", line 218, in main
    res = fit.fit_pg(data.data,args,M=M)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/fit.py", line 241, in __init__
    self.jackknife = jackknife.jackknife(close_call,data,res,args)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py", line 19, in __init__
    self.psuedovalues, self.delete_values = self.jackknife(f,x,r)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py", line 44, in jackknife
    k = np.ones((x.shape[0]),dtype=np.bool)
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 319, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
Popcorn version 1.0
(C) 2015-2019 Brielin C Brown
University of California, Berkeley
GNU General Public License v3

Invoking command: python /usr/local/bin/popcorn fit -v 1 --gen_effect --cfile /content/Popcorn/EUR_EAS_all_gen_eff.cscore --sfile1 EUR.txt.gz --sfile2 EAS.txt.gz /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/result/SLE_EUR_EAS
Beginning analysis at Sun Jul 28 14:40:17 2024
Analyzing a pair of traits in two populations
5723320 4297754 SNPs detected in input.
2735919 SNPs remaining after merging with score file.
2735919 SNPs remaining after filtering on AF and self-compliment SNPs.
Initial estimate:
       Val (obs)  SE
h1^2   0.162018 NaN
h2^2   0.132732 NaN
pg     1.038895 NaN
Performing jackknife estimation of the standard error using 200 blocks of size 13679 .
Jackknife iter: 1 /usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py:44: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  k = np.ones((x.shape[0]),dtype=np.bool)
Traceback (most recent call last):
  File "/usr/local/bin/popcorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/popcorn/__main__.py", line 218, in main
    res = fit.fit_pg(data.data,args,M=M)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/fit.py", line 241, in __init__
    self.jackknife = jackknife.jackknife(close_call,data,res,args)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py", line 19, in __init__
    self.psuedovalues, self.delete_values = self.jackknife(f,x,r)
  File "/usr/local/lib/python3.10/dist-packages/popcorn/jackknife.py", line 44, in jackknife
    k = np.ones((x.shape[0]),dtype=np.bool)
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 319, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
Popcorn version 1.0
(C) 2015-2019 Brielin C Brown
University of California, Berkeley
GNU General Public License v3

Invoking command: python /usr/local/bin/popcorn fit -v 1 --gen_effect --cfile /content/Popcorn/EUR_EAS_all_gen_eff.cscore --sfile1 EUR.txt.gz --sfile2 EAS.txt.gz /content/drive/MyDrive/Popcorn/SLE_EUR_EAS/result/SLE_EUR_EAS
Beginning analysis at Sun Jul 28 14:45:06 2024
Analyzing a pair of traits in two populations
5723320 4297754 SNPs detected in input.
2735919 SNPs remaining after merging with score file.
2735919 SNPs remaining after filtering on AF and self-compliment SNPs.
Initial estimate:
       Val (obs)  SE
h1^2   0.162018 NaN
h2^2   0.132732 NaN
pg     1.038895 NaN
Performing jackknife estimation of the standard error using 200 blocks of size 13679 .
Jackknife iter: 1 Jackknife iter: 2 Jackknife iter: 3 Jackknife iter: 4 Jackknife iter: 5 Jackknife iter: 6 Jackknife iter: 7 Jackknife iter: 8 Jackknife iter: 9 Jackknife iter: 10 Jackknife iter: 11 Jackknife iter: 12 Jackknife iter: 13 Jackknife iter: 14 Jackknife iter: 15 Jackknife iter: 16 Jackknife iter: 17 Jackknife iter: 18 Jackknife iter: 19 Jackknife iter: 20 Jackknife iter: 21 Jackknife iter: 22 Jackknife iter: 23 Jackknife iter: 24 Jackknife iter: 25 Jackknife iter: 26 Jackknife iter: 27 Jackknife iter: 28 Jackknife iter: 29 Jackknife iter: 30 Jackknife iter: 31 Jackknife iter: 32 Jackknife iter: 33 Jackknife iter: 34 Jackknife iter: 35 Jackknife iter: 36 Jackknife iter: 37 Jackknife iter: 38 Jackknife iter: 39 Jackknife iter: 40 Jackknife iter: 41 Jackknife iter: 42 Jackknife iter: 43 Jackknife iter: 44 Jackknife iter: 45 Jackknife iter: 46 Jackknife iter: 47 Jackknife iter: 48 Jackknife iter: 49 Jackknife iter: 50 Jackknife iter: 51 Jackknife iter: 52 Jackknife iter: 53 Jackknife iter: 54 Jackknife iter: 55 Jackknife iter: 56 Jackknife iter: 57 Jackknife iter: 58 Jackknife iter: 59 Jackknife iter: 60 Jackknife iter: 61 Jackknife iter: 62 Jackknife iter: 63 Jackknife iter: 64 Jackknife iter: 65 Jackknife iter: 66 Jackknife iter: 67 Jackknife iter: 68 Jackknife iter: 69 Jackknife iter: 70 Jackknife iter: 71 Jackknife iter: 72 Jackknife iter: 73 Jackknife iter: 74 Jackknife iter: 75 Jackknife iter: 76 Jackknife iter: 77 Jackknife iter: 78 Jackknife iter: 79 Jackknife iter: 80 Jackknife iter: 81 Jackknife iter: 82 Jackknife iter: 83 Jackknife iter: 84 Jackknife iter: 85 Jackknife iter: 86 Jackknife iter: 87 Jackknife iter: 88 Jackknife iter: 89 Jackknife iter: 90 Jackknife iter: 91 Jackknife iter: 92 Jackknife iter: 93 Jackknife iter: 94 Jackknife iter: 95 Jackknife iter: 96 Jackknife iter: 97 Jackknife iter: 98 Jackknife iter: 99 Jackknife iter: 100 Jackknife iter: 101 Jackknife iter: 102 Jackknife iter: 103 Jackknife iter: 104 Jackknife iter: 105 Jackknife iter: 106 Jackknife iter: 107 Jackknife iter: 108 Jackknife iter: 109 Jackknife iter: 110 Jackknife iter: 111 Jackknife iter: 112 Jackknife iter: 113 Jackknife iter: 114 Jackknife iter: 115 Jackknife iter: 116 Jackknife iter: 117 Jackknife iter: 118 Jackknife iter: 119 Jackknife iter: 120 Jackknife iter: 121 Jackknife iter: 122 Jackknife iter: 123 Jackknife iter: 124 Jackknife iter: 125 Jackknife iter: 126 Jackknife iter: 127 Jackknife iter: 128 Jackknife iter: 129 Jackknife iter: 130 Jackknife iter: 131 Jackknife iter: 132 Jackknife iter: 133 Jackknife iter: 134 Jackknife iter: 135 Jackknife iter: 136 Jackknife iter: 137 Jackknife iter: 138 Jackknife iter: 139 Jackknife iter: 140 Jackknife iter: 141 Jackknife iter: 142 Jackknife iter: 143 Jackknife iter: 144 Jackknife iter: 145 Jackknife iter: 146 Jackknife iter: 147 Jackknife iter: 148 Jackknife iter: 149 Jackknife iter: 150 Jackknife iter: 151 Jackknife iter: 152 Jackknife iter: 153 Jackknife iter: 154 Jackknife iter: 155 Jackknife iter: 156 Jackknife iter: 157 Jackknife iter: 158 Jackknife iter: 159 Jackknife iter: 160 Jackknife iter: 161 Jackknife iter: 162 Jackknife iter: 163 Jackknife iter: 164 Jackknife iter: 165 Jackknife iter: 166 Jackknife iter: 167 Jackknife iter: 168 Jackknife iter: 169 Jackknife iter: 170 Jackknife iter: 171 Jackknife iter: 172 Jackknife iter: 173 Jackknife iter: 174 Jackknife iter: 175 Jackknife iter: 176 Jackknife iter: 177 Jackknife iter: 178 Jackknife iter: 179 Jackknife iter: 180 Jackknife iter: 181 Jackknife iter: 182 Jackknife iter: 183 Jackknife iter: 184 Jackknife iter: 185 Jackknife iter: 186 Jackknife iter: 187 Jackknife iter: 188 Jackknife iter: 189 Jackknife iter: 190 Jackknife iter: 191 Jackknife iter: 192 Jackknife iter: 193 Jackknife iter: 194 Jackknife iter: 195 Jackknife iter: 196 Jackknife iter: 197 Jackknife iter: 198 Jackknife iter: 199 Jackknife iter: 200 
      Val (obs)        SE         Z         P (Z)
h1^2   0.162018  0.029780  5.440459  5.314344e-08
h2^2   0.132732  0.046638  2.845981  4.427482e-03
pge    1.038895  0.240950 -0.161422  8.717611e-01
Analysis finished at Sun Jul 28 15:09:57 2024
Total time elapsed: 1490.13
